# Automatically update CHANGELOG.md and create release when tag is pushed
name: Release

on: 
  push:
    branches:

jobs:
  release:
    if: contains(github.event.head_commit.message, '[versionup]') == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.TOKEN}}
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    # - run: |
    #     git config --global user.email "tamuhey@gmail.com"
    #     git config --global user.name "tamuhey"
    #     git remote add github "https://tamuhey:${{secrets.TOKEN}}@github.com/$GITHUB_REPOSITORY.git"
    - name: tag
      shell: bash
      run: |
        TAG=$(git log -1 --pretty=%B | cut -f 4 -d" " | head -1)
        git tag $TAG
        git push origin $TAG
    - run: npm install github-release-notes -g
    - run: gren changelog --override --token ${{secrets.TOKEN}} 
    - run: gren release --override --token ${{secrets.TOKEN}}
    - name: commit
      run: |
        git add .
        git commit -m "Update Changelog"
        git push github HEAD:${GITHUB_REF}