# Automatically update CHANGELOG.md and create release when tag is pushed
name: Release

on: 
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+.dev[0-9]+'

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip ci]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm install github-release-notes -g
    - run: gren release --override --token ${ GITHUB_TOKEN }
    - run: gren changelog --override --token ${ GITHUB_TOKEN }
    - name: commit
      run: |
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update dependencies"
        git push github HEAD:${GITHUB_REF}
    - name: tag
      shell: bash
      run: |
        TAG=$(git log -1 --pretty=%B | cut -f 2 -d" " | head -1)
        git tag $TAG
        git push origin $TAG
